### ISSUE TITLE
Not being able to decode basic authorization header

### ISSUE THREAD

**Issue by romfrolov** [evbox/station-simulator#41]
I'm struggling to decode authorization token received from station simulator and I'm not sure whether an issue is on my side or simulators side.

Received auth token (encoded): `RVZCLVAxNzM5MDg2NjoBI6s=`
Received auth token (decoded): `EVB-P17390866:#«`

My auth token (encoded): `RVZCLVAxNzM5MDg2NjowMTIzYWI=`
My auth token (decoded): `EVB-P17390866:0123ab`

**configuration.yml**
```
stations:
  - id: EVB-P17390866
    basicAuthPassword: 0123ab
    ...
```
